import type { DengueReport, ManagementBrief } from './types';
import { REGION_EN } from './types';
import { toEnglishLongDate } from './bengali';

const esc = (s: string) =>
  s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!);

/**
 * A self-contained HTML file. It prints cleanly to PDF from any browser, which
 * is what people actually do with these, and it keeps the figures next to the
 * narrative so the brief can be checked without opening the workbook.
 */
export function briefToHtml(report: DengueReport, brief: ManagementBrief): string {
  const bn = brief.language === 'bn';
  const rows = report.rows
    .map(
      (r) =>
        `<tr><td>${esc(REGION_EN[r.key])}</td><td>${r.admitted24h ?? '—'}</td><td>${r.deaths24h ?? '—'}</td><td>${r.totalAdmitted ?? '—'}</td><td>${r.totalDeaths ?? '—'}</td><td>${r.currentlyAdmitted ?? '—'}</td></tr>`,
    )
    .join('');

  const list = (items: string[]) => items.map((i) => `<li>${esc(i)}</li>`).join('');

  return `<!doctype html>
<html lang="${bn ? 'bn' : 'en'}">
<meta charset="utf-8">
<title>Dengue situation brief — ${esc(report.date)}</title>
<style>
  @page { margin: 18mm 16mm; }
  body { font: 13px/1.6 "IBM Plex Sans", "Nirmala UI", system-ui, sans-serif; color: #10202F; max-width: 780px; margin: 32px auto; padding: 0 20px; }
  h1 { font-size: 19px; margin: 0 0 4px; }
  h2 { font-size: 13px; color: #134472; border-bottom: 1px solid #D9E0E8; padding-bottom: 5px; margin: 26px 0 10px; }
  .meta { color: #61798F; font-size: 12px; margin-bottom: 22px; }
  .lead { font-size: 14px; font-weight: 600; }
  table { border-collapse: collapse; width: 100%; font-size: 12px; font-variant-numeric: tabular-nums; }
  th, td { border: 1px solid #D9E0E8; padding: 5px 8px; text-align: right; }
  th:first-child, td:first-child { text-align: left; }
  th { background: #EAF1F8; font-weight: 600; }
  ul, ol { padding-left: 20px; margin: 0; }
  li { margin-bottom: 6px; }
  .flag { display: inline-block; font-size: 10.5px; padding: 1px 6px; border-radius: 2px; margin-right: 6px; }
  .high { background: #FBEDEC; color: #B3302A; } .moderate { background: #FBF3E7; color: #A9702A; } .watch { background: #EAF1F8; color: #1B5E9C; }
  footer { margin-top: 30px; padding-top: 12px; border-top: 1px solid #D9E0E8; color: #61798F; font-size: 11px; }
</style>
<h1>${bn ? 'ডেঙ্গু পরিস্থিতি সংক্ষেপ' : 'Dengue situation brief'}</h1>
<p class="meta">${esc(toEnglishLongDate(report.date))} · Source: ${esc(report.extraction.method === 'manual' ? 'entered manually' : 'DGHS daily press release')} · Extraction ${(report.extraction.confidence * 100).toFixed(0)}% (${esc(report.extraction.method)})</p>

<p class="lead">${esc(brief.headline)}</p>
<p>${esc(brief.situation)}</p>

<h2>${bn ? 'মূল পর্যবেক্ষণ' : 'Key findings'}</h2><ul>${list(brief.keyFindings)}</ul>
<h2>${bn ? 'ভৌগোলিক চিত্র' : 'Geographic pattern'}</h2><p>${esc(brief.geographicPattern)}</p>
${
  brief.riskFlags?.length
    ? `<h2>${bn ? 'ঝুঁকি' : 'Risk flags'}</h2><ul style="list-style:none;padding-left:0">${brief.riskFlags
        .map((r) => `<li><span class="flag ${r.level}">${r.level}</span>${esc(r.text)}</li>`)
        .join('')}</ul>`
    : ''
}
<h2>${bn ? 'করণীয়' : 'Recommended actions'}</h2><ol>${list(brief.recommendations)}</ol>
${brief.dataCaveats?.length ? `<h2>${bn ? 'তথ্যের সীমাবদ্ধতা' : 'What these numbers cannot tell you'}</h2><ul>${list(brief.dataCaveats)}</ul>` : ''}

<h2>${bn ? 'বিভাগভিত্তিক তথ্য' : 'Division-wise figures'}</h2>
<table>
  <thead><tr><th>Division</th><th>24h admitted</th><th>24h deaths</th><th>Total admitted</th><th>Total deaths</th><th>In hospital</th></tr></thead>
  <tbody>${rows}
    <tr><th>Total</th><th>${report.totals.admitted24h ?? '—'}</th><th>${report.totals.deaths24h ?? '—'}</th><th>${report.totals.totalAdmitted ?? '—'}</th><th>${report.totals.totalDeaths ?? '—'}</th><th>${report.totals.currentlyAdmitted ?? '—'}</th></tr>
  </tbody>
</table>

<footer>
  Generated by dengue_daily_report${report.sourceUrl ? ` from ${esc(report.sourceUrl)}` : ''}.
  Figures are hospitalised cases reported to the DGHS control room and are not population incidence.
  Verify against the source before circulating.
</footer>
</html>`;
}

export function downloadFile(filename: string, content: BlobPart, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
